from __future__ import annotations


POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT PRIMARY KEY,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS telegram_accounts (
  telegram_user_id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  username TEXT NOT NULL DEFAULT '',
  first_name TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_telegram_accounts_user_id ON telegram_accounts(user_id);

CREATE TABLE IF NOT EXISTS user_profile (
  user_id BIGINT PRIMARY KEY,
  preferred_name TEXT,
  preferred_title TEXT,
  mode TEXT,
  chat_locked INTEGER NOT NULL DEFAULT 0,
  lock_reason TEXT NOT NULL DEFAULT '',
  mode_picked INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_settings (
  user_id BIGINT PRIMARY KEY,
  model TEXT NOT NULL,
  image_model TEXT NOT NULL DEFAULT '',
  image_provider TEXT NOT NULL DEFAULT 'openrouter'
);

CREATE TABLE IF NOT EXISTS conversations (
  conversation_ref TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  status TEXT NOT NULL DEFAULT 'active',
  is_default INTEGER NOT NULL DEFAULT 0,
  active_mode TEXT NOT NULL DEFAULT 'basic',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversations_single_default_per_user
  ON conversations(user_id)
  WHERE is_default = 1;
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL DEFAULT 'basic',
  role TEXT NOT NULL CHECK(role IN ('user','assistant')),
  content TEXT NOT NULL,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_ref ON messages(conversation_ref);

CREATE TABLE IF NOT EXISTS user_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL DEFAULT 'basic',
  role TEXT NOT NULL CHECK(role IN ('user','assistant')),
  content TEXT NOT NULL,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_messages_user_id ON user_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_user_messages_user_id_mode ON user_messages(user_id, mode);
CREATE INDEX IF NOT EXISTS idx_user_messages_conversation_ref ON user_messages(conversation_ref);

CREATE TABLE IF NOT EXISTS mode_state (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  state_json TEXT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_mode_state_conversation_ref ON mode_state(conversation_ref);

CREATE TABLE IF NOT EXISTS conversation_mode_state (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  state_json TEXT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_conversation_mode_state_conversation_ref ON conversation_mode_state(conversation_ref);

CREATE TABLE IF NOT EXISTS mode_locks (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  locked INTEGER NOT NULL DEFAULT 0,
  reason TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_mode_locks_conversation_ref ON mode_locks(conversation_ref);

CREATE TABLE IF NOT EXISTS conversation_mode_lock (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  locked INTEGER NOT NULL DEFAULT 0,
  reason TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_conversation_mode_lock_conversation_ref ON conversation_mode_lock(conversation_ref);

CREATE TABLE IF NOT EXISTS conversation_photo_gate (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  score INTEGER NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_ask_ts BIGINT NOT NULL DEFAULT 0,
  cooldown_until_ts BIGINT NOT NULL DEFAULT 0,
  awaiting_context INTEGER NOT NULL DEFAULT 0,
  context_asked_ts BIGINT NOT NULL DEFAULT 0,
  awaiting_image_prompt INTEGER NOT NULL DEFAULT 0,
  image_cooldown_until_ts BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, conversation_ref)
);
CREATE INDEX IF NOT EXISTS idx_conversation_photo_gate_conversation_ref ON conversation_photo_gate(conversation_ref);

CREATE TABLE IF NOT EXISTS jobs (
  job_id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  result_ref TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_jobs_user_id ON jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_jobs_conversation_ref ON jobs(conversation_ref);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts BIGINT NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  event_type TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT '',
  ok INTEGER NOT NULL DEFAULT 1,
  note TEXT NOT NULL DEFAULT '',
  conversation_ref TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_user_id ON events(user_id);

CREATE TABLE IF NOT EXISTS user_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts BIGINT NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  chat_id BIGINT NOT NULL DEFAULT 0,
  username TEXT NOT NULL DEFAULT '',
  first_name TEXT NOT NULL DEFAULT '',
  event_type TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT '',
  mode_from TEXT NOT NULL DEFAULT '',
  mode_to TEXT NOT NULL DEFAULT '',
  message_id BIGINT NOT NULL DEFAULT 0,
  text_len INTEGER NOT NULL DEFAULT 0,
  photo_provider TEXT NOT NULL DEFAULT '',
  photo_model TEXT NOT NULL DEFAULT '',
  ok INTEGER NOT NULL DEFAULT 1,
  note TEXT NOT NULL DEFAULT '',
  conversation_ref TEXT,
  llm_provider TEXT NOT NULL DEFAULT '',
  llm_model TEXT NOT NULL DEFAULT '',
  prompt_tokens INTEGER NOT NULL DEFAULT 0,
  completion_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens INTEGER NOT NULL DEFAULT 0,
  tokens_source TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_user_events_user_ts ON user_events(user_id, ts);
CREATE INDEX IF NOT EXISTS idx_user_events_ts ON user_events(ts);
CREATE INDEX IF NOT EXISTS idx_user_events_type ON user_events(event_type);

CREATE TABLE IF NOT EXISTS relationship_state (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  state_json TEXT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_relationship_state_conversation_ref ON relationship_state(conversation_ref);

CREATE TABLE IF NOT EXISTS conversation_relationship_state (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  conversation_ref TEXT NOT NULL REFERENCES conversations(conversation_ref),
  mode TEXT NOT NULL,
  state_json TEXT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (user_id, conversation_ref, mode)
);
CREATE INDEX IF NOT EXISTS idx_conversation_relationship_state_conversation_ref ON conversation_relationship_state(conversation_ref);

CREATE TABLE IF NOT EXISTS sessions (
  session_token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  issued_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS plans (
  plan_id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  tier TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS entitlements (
  entitlement_id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  plan_id TEXT REFERENCES plans(plan_id),
  tier TEXT NOT NULL,
  starts_at BIGINT NOT NULL,
  expires_at BIGINT,
  source TEXT NOT NULL,
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_entitlements_user_id ON entitlements(user_id);
CREATE INDEX IF NOT EXISTS idx_entitlements_plan_id ON entitlements(plan_id);

CREATE TABLE IF NOT EXISTS usage_counters (
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  counter_key TEXT NOT NULL,
  window_start BIGINT NOT NULL,
  window_end BIGINT NOT NULL,
  value INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, counter_key, window_start)
);

CREATE TABLE IF NOT EXISTS access_grants (
  grant_id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(user_id),
  granted_by TEXT NOT NULL,
  grant_type TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  revoked_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_access_grants_user_id ON access_grants(user_id);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE mode_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_mode_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE mode_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_mode_lock ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_photo_gate ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE relationship_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_relationship_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE entitlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_grants ENABLE ROW LEVEL SECURITY;
"""


POSTGRES_LEAST_PRIVILEGE_SQL = """
-- Run as a Supabase/Postgres owner role after replacing placeholders.
GRANT CONNECT ON DATABASE lina TO lina_app;
GRANT USAGE ON SCHEMA public TO lina_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO lina_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lina_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lina_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO lina_app;
"""
